### ISSUE TITLE
Move Debia deployment to Docker

### ISSUE THREAD

**Issue by Devnol** [cytrus-re/debia#2]
Step 1 is making a Dockerfile, that'll be assigned to Oxy.
Step 2 is making a GCE server with docker support and making an action that pushes to GitHub Container Registry and pulls the image to GCE, that'll be on me.

**Comment by Oxygemo** [comment]
hi)

**Comment by Oxygemo** [comment]
Seems done

**Comment by Devnol** [comment]
it isn't. I have to test it too

**Comment by Devnol** [comment]
It's technically done now apart from production deployment, so I'll just lower the priority.

**Comment by Devnol** [comment]
Oh you did, even cooler

**Comment by ghost** [comment]
Done!

**Comment by Devnol** [comment]
23 days of pain, sufferring and cock and ball torture
